# Generated by Django 3.2.7 on 2021-10-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0002_auto_20210822_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='carOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter your Firstname', max_length=200, null=True, verbose_name='Firstame')),
                ('last_name', models.CharField(help_text='Please enter your Lastname', max_length=200, null=True, verbose_name='Lastame')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('information', models.TextField(help_text='Some additonal information about you', max_length=1000, null=True)),
                ('image_one', models.ImageField(null=True, upload_to='images/', verbose_name='Car Picture')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car')),
            ],
        ),
    ]
